# Default values for elasticsearch-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: upmcenterprises/docker-elasticsearch-kubernetes
  tag: 6.1.3_0
  #pullSecret: test

clientReplicas: 1
masterReplicas: 1
dataReplicas: 1
dataVolumeSize: 1Gi
javaOpts: "-Xms256m -Xmx256m"

# Deploy data nodes across zones
zones:
  - us-east-1c
  - us-east-1d
  - us-east-1e
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1f

snapshot:
  enabled: true
  bucketName: elasticsnapshots99
  schedule: "@every 2m"
  authentication:
    enabled: false
    password: test
    username: test

storage:
  # e.g. gp2 for AWS
  type: gp2
  # e.g. kubernetes.io/aws-ebs for AWS
  classProvisioner: kubernetes.io/aws-ebs
  # Retain or Delete
  reclaimPolicy: Delete

kibana:
  enabled: true
  image: docker.elastic.co/kibana/kibana-oss:6.1.3

cerebro:
  enabled: true
  image: upmcenterprises/cerebro:0.6.8

statsd:
  enabled: false
  host: ""

resources:
  requests:
    memory: 512Mi
    cpu: 500m
  limits:
    memory: 1024Mi
    cpu: '1'
